# Generated by Django 5.0.4 on 2024-10-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscopesign',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='horoscope_images/'),
        ),
        migrations.AddField(
            model_name='horoscopesign',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='horoscope_images/'),
        ),
    ]
