# Generated by Django 4.2.7 on 2024-10-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_horoscopesign_icon_image_horoscopesign_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscopesign',
            name='characteristics_of_thehorscope',
            field=models.TextField(blank=True, null=True),
        ),
    ]
