version: '3'

services:
  web:
    build: ./backend
    restart: always
    command: gunicorn alabrage.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/code
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery:
    build: ./backend
    restart: always
    command: celery -A alabrage worker -l info
    volumes:
      - ./backend:/code
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery-beat:
    build: ./backend
    restart: always
    command: celery -A alabrage beat -l info
    volumes:
      - ./backend:/code
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: "redis:alpine"
    restart: always

  frontend:
    build: ./frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://15.185.205.92:8000
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: